const rawFetch=window.fetch.bind(window);
const state={data:null,sessionId:null,updateDocumentId:null,userId:null,user:null,token:localStorage.getItem('devpilot-token')};
window.fetch=async(input,init={})=>{const headers=new Headers(init.headers||{});if(state.token)headers.set('Authorization',`Bearer ${state.token}`);const response=await rawFetch(input,{...init,headers});if(response.status===401&&String(input)!=='/api/v1/auth/login')showLogin('登录已失效，请重新登录。');return response};
const activeSessionKey=userId=>`devpilot-active-session:${userId}`;
function rememberActiveSession(sessionId){state.sessionId=sessionId;if(sessionId)localStorage.setItem(activeSessionKey(state.userId),sessionId);else localStorage.removeItem(activeSessionKey(state.userId))}
function beginNewSession(){state.sessionId=null;localStorage.setItem(activeSessionKey(state.userId),'__new__')}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const titles={overview:['OPERATIONS / OVERVIEW','运行总览'],assistant:['AGENT / COLLABORATION','智能协同'],deployments:['RELEASES / HISTORY','发布记录'],incidents:['RESPONSE / WORKSPACE','故障与工单'],knowledge:['KNOWLEDGE / SOURCES','知识库']};
const fmt=v=>v?new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)).replaceAll('/','-'):'—';
const duration=(a,b)=>{if(!a||!b)return '—';const s=Math.max(0,(new Date(b)-new Date(a))/1000);return s>=60?`${Math.round(s/60)} min`:`${Math.round(s)} s`};
const badge=v=>`<span class="badge ${v||'UNKNOWN'}">${v||'UNKNOWN'}</span>`;
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function route(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${page}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#page-kicker').textContent=titles[page][0];$('#page-title').textContent=titles[page][1];location.hash=page;$('.sidebar').classList.remove('open')}
$$('[data-page]').forEach(b=>b.onclick=()=>route(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>route(b.dataset.go));$('#menu').onclick=()=>$('.sidebar').classList.toggle('open');
function render(){const d=state.data,s=d.summary;$('#metrics').innerHTML=[['服务总数',s.services,'已纳入统一观测'],['健康服务',s.healthy_services,`${Math.round(s.healthy_services/Math.max(1,s.services)*100)}% 可用`],['未解决故障',s.open_incidents,s.open_incidents?'需要关注':'暂无风险'],['进行中工单',s.open_tickets,'协同处理中']].map(x=>`<div class="metric panel"><small>${x[0]}</small><strong>${String(x[1]).padStart(2,'0')}</strong><span class="delta">${x[2]}</span></div>`).join('');
  $('#health-ratio').textContent=`${s.healthy_services} / ${s.services} healthy`;$('#service-list').classList.remove('loading');$('#service-list').innerHTML=d.services.map(x=>`<div class="service-row"><div class="service-name"><strong>${x.name}</strong><small>${x.owner_team}</small></div><span class="env">${x.environment}</span>${badge(x.status)}</div>`).join('')||'<div class="empty">暂无服务</div>';
  $('#recent-deployments').classList.remove('loading');$('#recent-deployments').innerHTML=d.deployments.slice(0,5).map(x=>`<div class="timeline-item ${x.status==='FAILED'?'fail':''}"><div class="timeline-line"></div><div class="timeline-copy"><strong>${x.service_name} · ${x.version}</strong><p>${x.operator_name||'system'} · ${x.environment}</p></div><span class="timeline-time">${fmt(x.started_at)}</span></div>`).join('');
  $('#deployment-table').innerHTML=d.deployments.map(x=>`<tr><td><strong>${x.service_name}</strong><small>${x.version}</small></td><td>${x.environment}</td><td>${badge(x.status)}</td><td>${x.operator_name||'—'}</td><td class="mono">${x.commit_sha||'—'}</td><td>${fmt(x.started_at)}</td><td>${duration(x.started_at,x.finished_at)}</td></tr>`).join('');
  $('#incident-list').innerHTML=d.incidents.map(x=>`<article class="issue"><div class="issue-top"><h4>${x.title}</h4>${badge(x.severity)}</div><p>${x.root_cause||'根因仍在调查中'}</p><div class="issue-foot"><span>${x.service_name}</span><span>${x.status} · ${fmt(x.started_at)}</span></div></article>`).join('')||'<div class="empty">暂无故障</div>';
  $('#ticket-list').innerHTML=d.tickets.map(x=>`<article class="issue"><div class="issue-top"><h4>${x.title}</h4>${badge(x.priority)}</div><p>负责人：${x.assignee||'待分配'}</p><div class="issue-foot"><span>${x.service_name||'通用任务'}</span><span>${x.status} · ${fmt(x.created_at)}</span></div></article>`).join('')||'<div class="empty">暂无工单</div>';
  $('#doc-count').textContent=`${d.documents.length} 个来源`;$('#document-list').innerHTML=d.documents.map(x=>`<div class="document"><span class="file-icon">${esc((x.doc_type||'DOC').toUpperCase())}</span><div><strong>${esc(x.title)}</strong><small>${esc(x.source_uri)} · v${x.version||1} · ${x.chunk_count||0} chunks</small></div>${badge(x.status)}<button class="doc-update" data-doc-id="${x.id}" data-doc-title="${esc(x.title)}" data-doc-source="${esc(x.source_uri)}">更新</button></div>`).join('')||'<div class="empty">还没有文档，上传第一份团队资料吧。</div>';filterKnowledgeDocuments();
}
async function load(){try{const [h,d,integrations]=await Promise.all([fetch('/health').then(r=>r.json()),fetch('/api/v1/dashboard').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}),fetch('/api/v1/integrations').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).catch(()=>({external_mcp:[]}))]);state.data=d;const components=h.components||{},checks=Object.values(components).filter(item=>item?.required!==false),healthy=item=>item===true||item?.status==='ok'||item?.status==='healthy'||item?.healthy===true,onlineCount=checks.filter(healthy).length,totalCount=checks.length,github=integrations.external_mcp?.find(item=>item.id==='github_mcp'),githubReady=Boolean(github?.configured);$('#system-title').textContent=h.ready?`核心依赖正常${totalCount?` · ${onlineCount}/${totalCount}`:''}`:(h.local_model_online?'核心服务在线':'部分依赖需要检查');$('#model-name').textContent=h.local_model_online?`${h.llm_model} · 可生成`:`${h.llm_model} · 使用结构化降级回答`;$('#system-pulse').classList.toggle('offline',!h.local_model_online);setAgentStatus('#status-model',h.local_model_online);setAgentStatus('#status-rag',healthy(components.qdrant));setAgentStatus('#status-memory',healthy(components.mysql));setAgentStatus('#status-mcp',githubReady);$('#github-mcp-dot').classList.toggle('online',githubReady);$('#github-mcp-state').textContent=githubReady?`${github.allowed_tools.length} 个只读工具 · 已配置`:'未配置 · 可选外部证据';render()}catch(e){toast('数据加载失败，请检查后端服务');console.error(e)}}
function setAgentStatus(selector,online){const el=$(selector);if(!el)return;el.classList.toggle('online',online);el.classList.toggle('offline',!online)}
$('#refresh').onclick=()=>{load();toast('正在刷新运行数据')};
const prompts=['订单服务怎么部署？','现在有哪些未解决故障？','order-service 最近 7 天部署情况怎么样？','结合失败发布和部署手册给我排查建议。'];$('#prompt-list').innerHTML=prompts.map(x=>`<button class="prompt">${x}</button>`).join('');$$('.prompt').forEach(x=>x.onclick=()=>{$('#chat-input').value=x.textContent;updateCount();$('#chat-input').focus()});
function addMessage(role,text,meta={}){const wrap=document.createElement('div');wrap.className=`message ${role}`;const safe=document.createElement('div');safe.className='bubble';const content=document.createElement('p');content.textContent=text;safe.appendChild(content);const modelTags=(meta.models||[]).map(x=>x.fallback?`${x.requested_model_role}→${x.served_model_role}`:`${x.served_model_role}:${x.agent_name}`);const qualityTag=meta.evidenceQuality?.status?`EVIDENCE ${meta.evidenceQuality.status.toUpperCase()} · ${Math.round((meta.evidenceQuality.score||0)*100)}%`:null;const tags=[meta.intent,meta.path,qualityTag,...(meta.agents||[]),...(meta.tools||[]),...modelTags].filter(Boolean);if(tags.length){const m=document.createElement('div');m.className='bubble-meta';tags.forEach(t=>{const s=document.createElement('span');s.className='trace-tag';s.textContent=t;m.appendChild(s)});safe.appendChild(m)}if(meta.citations?.length){const refs=document.createElement('div');refs.className='citation-list';meta.citations.forEach((c,i)=>{const s=document.createElement('span');s.textContent=`DOC ${i+1} · ${c.title||'未命名文档'}${c.chunk_id?` · chunk ${c.chunk_id}`:''}`;refs.appendChild(s)});safe.appendChild(refs)}if(meta.externalEvidence?.length){const refs=document.createElement('div');refs.className='external-evidence-list';meta.externalEvidence.forEach(item=>{const row=document.createElement(item.reference?'a':'span');row.className=`external-evidence ${item.status}`;row.textContent=`MCP · ${item.source} · ${item.status}${item.summary?` · ${item.summary}`:''}`;if(item.reference){row.href=item.reference;row.target='_blank';row.rel='noopener noreferrer'}refs.appendChild(row)});safe.appendChild(refs)}wrap.appendChild(safe);$('#messages').appendChild(wrap);$('#messages').scrollTop=$('#messages').scrollHeight;return wrap}
function updateCount(){const t=$('#chat-input');$('#char-count').textContent=`${t.value.length} / 4000`;t.style.height='auto';t.style.height=Math.min(t.scrollHeight,120)+'px'}$('#chat-input').oninput=updateCount;$('#chat-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chat-form').requestSubmit()}};
$('#chat-form').onsubmit=async e=>{e.preventDefault();const input=$('#chat-input'),q=input.value.trim();if(!q)return;if(!state.sessionId)rememberActiveSession(crypto.randomUUID());const requestId=crypto.randomUUID();input.value='';updateCount();addMessage('user',q);const waiting=addMessage('assistant','正在选择执行路径与专业 Agent');waiting.classList.add('pending');try{const r=await fetch('/api/v1/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,user_id:state.userId,session_id:state.sessionId,request_id:requestId})});if(!r.ok)throw Error((await r.text())||`HTTP ${r.status}`);const d=await r.json();rememberActiveSession(d.session_id);waiting.remove();addMessage('assistant',d.answer,{intent:d.intent,path:d.selected_path,agents:d.selected_agents,tools:d.tools_used,models:d.model_info,citations:d.citations,externalEvidence:d.external_evidence,evidenceQuality:d.evidence_quality});showContext(d.context_info);showMemory(d.memory);await Promise.all([loadSessions(),loadMemories()]);}catch(err){waiting.remove();addMessage('assistant',`请求失败：${err.message}`)}};
function showContext(info){if(!info)return;const used=(info.estimated_recent_tokens||0)+(info.estimated_summary_tokens||0),max=info.max_input_tokens||1,percent=Math.min(100,Math.round(used/max*100)),meter=$('.context-meter');$('#context-status').textContent=`${used} / ${max} tokens · ${info.window_message_count||0} 条窗口 · ${info.summarized_message_count||0} 条压缩`;$('#context-meter-fill').style.width=`${percent}%`;meter.setAttribute('aria-valuenow',String(percent));meter.title=`上下文预算已使用 ${percent}%`}
function showMemory(memory){const entities=memory?.entities||{},facts=memory?.user_facts||{},items=[];if(facts.name)items.push(`姓名 ${facts.name}`);if(entities.service)items.push(`服务 ${entities.service}`);if(entities.environment)items.push(`环境 ${entities.environment}`);if(entities.time_range_days)items.push(`范围 ${entities.time_range_days} 天`);if(memory?.active_goal)items.push(`目标 ${memory.active_goal.slice(0,36)}`);$('#memory-turns').textContent=`${memory?.updated_turns||0} turns`;$('#memory-items').innerHTML=items.length?items.map(x=>`<span>${esc(x)}</span>`).join(''):'<small>尚未提取结构化记忆</small>'}
async function loadMemories(){try{const d=await fetch('/api/v1/memories').then(r=>{if(!r.ok)throw Error(r.status);return r.json()});$('#long-memory-items').innerHTML=d.memories.length?d.memories.map(x=>`<span>${esc(x.memory_type)} · ${esc(x.content)} <button class="memory-delete" data-memory-id="${esc(x.id)}" title="删除这条记忆">×</button></span>`).join(''):'<small>暂无长期记忆</small>'}catch(e){$('#long-memory-items').innerHTML='<small>长期记忆加载失败</small>'}}
$('#reload-memories').onclick=loadMemories;
$('#long-memory-items').onclick=async e=>{const button=e.target.closest('[data-memory-id]');if(!button)return;const r=await fetch(`/api/v1/memories/${encodeURIComponent(button.dataset.memoryId)}`,{method:'DELETE'});if(r.ok){await loadMemories();toast('长期记忆已删除')}else toast('删除失败')};
$('#new-chat').onclick=()=>{beginNewSession();$('#messages').innerHTML='';addMessage('assistant','新会话已就绪。你想先了解什么？');$('#context-status').textContent='等待首次对话';showMemory(null);loadSessions();toast('已切换到新会话')};
function showLogin(message=''){state.token=null;state.user=null;state.userId=null;localStorage.removeItem('devpilot-token');$('#global-user').textContent='未登录';$('#global-tenant').textContent='SECURE ACCESS';$('#login-status').textContent=message;$('#login-overlay').hidden=false}
function applyUser(user){state.user=user;state.userId=user.id;$('#current-user').textContent=`${user.username} · ${user.role} · ${user.tenant}`;$('#global-user').textContent=user.username;$('#global-tenant').textContent=`${user.tenant} · ${user.role}`;$('#login-overlay').hidden=true}
$('#login-form').onsubmit=async e=>{e.preventDefault();$('#login-status').textContent='正在验证…';try{const r=await rawFetch('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenant:$('#login-tenant').value.trim(),username:$('#login-username').value.trim(),password:$('#login-password').value})});if(!r.ok)throw Error('租户、用户名或密码不正确');const d=await r.json();state.token=d.access_token;localStorage.setItem('devpilot-token',state.token);applyUser(d.user);await load();await loadSessions(true)}catch(err){showLogin(err.message)}};
function logout(){beginNewSession();showLogin('已安全退出。')}
$('#switch-user').onclick=logout;$('#logout').onclick=logout;
async function openSession(sessionId,{silent=false}={}){try{const d=await fetch(`/api/v1/sessions/${sessionId}?user_id=${encodeURIComponent(state.userId)}&limit=100`).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});rememberActiveSession(d.session_id);$('#messages').innerHTML='';d.messages.forEach(x=>{if(x.role==='user'||x.role==='assistant')addMessage(x.role,x.content)});showContext(d.context_state?.context_stats);showMemory(d.context_state?.memory);await loadSessions();if(!silent)toast('会话已恢复');return true}catch(err){if(localStorage.getItem(activeSessionKey(state.userId))===sessionId)rememberActiveSession(null);if(!silent)toast(`会话加载失败：${err.message}`);return false}}
async function loadSessions(restore=false){try{const d=await fetch(`/api/v1/sessions?user_id=${encodeURIComponent(state.userId)}&limit=12`).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});const saved=localStorage.getItem(activeSessionKey(state.userId));const explicitNew=saved==='__new__';const ownedSaved=!explicitNew&&saved&&d.sessions.some(x=>x.id===saved);if(saved&&!explicitNew&&!ownedSaved)localStorage.removeItem(activeSessionKey(state.userId));const restoreId=ownedSaved?saved:(!explicitNew?d.sessions[0]?.id:null);$('#session-list').innerHTML=d.sessions.map(x=>`<button class="session-item ${x.id===state.sessionId?'active':''}" data-session="${x.id}"><strong>${esc(x.title||'未命名会话')}</strong><small>${x.message_count} 条 · ${fmt(x.last_active_at)}</small></button>`).join('')||'<small>暂无历史会话</small>';if(restore&&restoreId)await openSession(restoreId,{silent:true})}catch(e){$('#session-list').innerHTML='<small>会话加载失败</small>'}}
$('#reload-sessions').onclick=loadSessions;
$('#session-list').onclick=async e=>{const button=e.target.closest('[data-session]');if(!button)return;await openSession(button.dataset.session)};
function resetUploadMode(){state.updateDocumentId=null;$('#upload-mode').textContent='ADD KNOWLEDGE';$('#upload-title').textContent='扩展团队知识库';$('#upload-button').textContent='选择文档上传';$('#cancel-update').hidden=true;$('#doc-title-input').value='';$('#doc-source-input').value=''}
function filterKnowledgeDocuments(){const input=$('#knowledge-search');if(!input)return;const query=input.value.trim().toLocaleLowerCase(),rows=$$('#document-list .document');let visible=0;rows.forEach(row=>{const matched=!query||row.textContent.toLocaleLowerCase().includes(query);row.hidden=!matched;if(matched)visible++});if(state.data)$('#doc-count').textContent=query?`${visible} / ${state.data.documents.length} 个来源`:`${state.data.documents.length} 个来源`}
$('#knowledge-search').oninput=filterKnowledgeDocuments;
$('#document-list').onclick=e=>{const button=e.target.closest('.doc-update');if(!button)return;state.updateDocumentId=button.dataset.docId;$('#upload-mode').textContent='UPDATE KNOWLEDGE';$('#upload-title').textContent=`更新文档 #${state.updateDocumentId}`;$('#upload-button').textContent='选择新版本文件';$('#cancel-update').hidden=false;$('#doc-title-input').value=button.dataset.docTitle;$('#doc-source-input').value=button.dataset.docSource;$('#file-input').click()};
$('#cancel-update').onclick=resetUploadMode;$('#upload-button').onclick=()=>$('#file-input').click();$('#file-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;const btn=$('#upload-button'),status=$('#upload-status');btn.disabled=true;status.textContent=`正在${state.updateDocumentId?'更新':'索引'} ${file.name}…`;const body=new FormData();body.append('file',file);if($('#doc-title-input').value.trim())body.append('title',$('#doc-title-input').value.trim());if($('#doc-source-input').value.trim())body.append('source_uri',$('#doc-source-input').value.trim());const endpoint=state.updateDocumentId?`/api/v1/documents/${state.updateDocumentId}`:'/api/v1/documents/ingest';try{const r=await fetch(endpoint,{method:state.updateDocumentId?'PUT':'POST',body});if(!r.ok)throw Error(await r.text());const d=await r.json();status.textContent=d.skipped?'内容校验值相同，无需重复索引。':`${d.updated?'更新':'新增'}完成：已生成 ${d.chunks} 个知识块。`;resetUploadMode();await load();toast('知识库已更新')}catch(err){status.textContent=`处理失败：${err.message}`}finally{btn.disabled=false;e.target.value=''}};
async function bootstrap(){route((location.hash.slice(1) in titles)?location.hash.slice(1):'overview');if(!state.token){showLogin();return}try{const r=await rawFetch('/api/v1/auth/me',{headers:{Authorization:`Bearer ${state.token}`}});if(!r.ok)throw Error('登录已过期');applyUser(await r.json());await Promise.all([load(),loadMemories()]);await loadSessions(true)}catch(err){showLogin(err.message)}}
function tick(){const now=new Date();$('#clock').textContent=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(now)}tick();setInterval(tick,30000);bootstrap();
