USE devpilot;

CREATE TABLE IF NOT EXISTS tenant (
  id CHAR(36) PRIMARY KEY,
  slug VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  status ENUM('ACTIVE','DISABLED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS app_user (
  id CHAR(36) PRIMARY KEY,
  tenant_id CHAR(36) NOT NULL,
  username VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('ADMIN','MEMBER') NOT NULL DEFAULT 'MEMBER',
  status ENUM('ACTIVE','DISABLED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_tenant FOREIGN KEY(tenant_id) REFERENCES tenant(id),
  UNIQUE KEY uk_tenant_username(tenant_id,username)
) ENGINE=InnoDB;

ALTER TABLE kb_document ADD COLUMN IF NOT EXISTS tenant_id CHAR(36) NULL AFTER id;
ALTER TABLE kb_document ADD COLUMN IF NOT EXISTS owner_user_id CHAR(36) NULL AFTER tenant_id;
ALTER TABLE kb_document ADD COLUMN IF NOT EXISTS visibility ENUM('TENANT','PRIVATE') NOT NULL DEFAULT 'TENANT' AFTER owner_user_id;

CREATE TABLE IF NOT EXISTS kb_document_acl (
  document_id BIGINT NOT NULL,
  user_id CHAR(36) NOT NULL,
  permission ENUM('READ','WRITE') NOT NULL DEFAULT 'READ',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(document_id,user_id),
  CONSTRAINT fk_acl_document FOREIGN KEY(document_id) REFERENCES kb_document(id) ON DELETE CASCADE,
  CONSTRAINT fk_acl_user FOREIGN KEY(user_id) REFERENCES app_user(id) ON DELETE CASCADE
) ENGINE=InnoDB;
